config/routes.rb
TheaterApp::Application.routes.draw do
  match "signup" => 'users#new', :as => "signup"
  match "login" => 'sessions#new', :as => "login"
  match "logout" => 'sessions#destroy', :as => "logout"

  get "showtimes/:showtime_id/seats/:id/save/" => 'seats#save', :as => 'save_seat'
  get "showtimes/:showtime_id/seats/:id/give_up_seat/" => 'seats#give_up_seat', :as => 'give_up_seat'

  resources :users
  resources :movies
  resources :showtimes do
    resources :seats
  end
  resources :sessions, :except => [:edit, :update, :index]

  root :to => "movies#index"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  is_admin        :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  has_secure_password

  has_many :seats
  has_many :showtimes, :through => :seats

  attr_accessible :email, :password, :password_confirmation

  validates :email, :uniqueness => true
  validates :email, :format => /@/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 skip_before_filter :require_authentication, :only => [:new, :create]
 skip_before_filter :require_admin_authentication, :only => [:new, :create, :edit, :update, :show]


  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        if !params[:seat_id].nil?
          @seat = Seat.find(params[:seat_id]) #if a seat param comes in (i.e. page was rendered from a non-logged-in user that wanted to sign up)
          @seat.update_attributes(:user_id => @user.id) #add user id to seat object
        end
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.js
      end
    end
  end

  def show
    @user = User.find(session[:user_id])
    @seats = Seat.where(:user_id => [@user.id])

    @seats_array = @seats.sort{
      |a,b| (a.showtime.date == b.showtime.date) ? a.showtime.movie.name <=> b.showtime.movie.name : a.showtime.date <=> b.showtime.date
    }

    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.js
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <% if !@seat.nil? %>
    <input type="hidden" name="seat_id" value="<%= @seat.id %>">
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>


<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<table>
  <tr>
    <th>Movie</th>
    <th>Showtime</th>
    <th>Seat</th>
    <th></th>
    <th></th>
    <!-- <th></th> -->
    <!-- <th></th> -->
  </tr>

<% @seats_array.each do |seat| %>
  <tr>
    <td><%= seat.showtime.movie.name %></td>
    <td><%= seat.showtime.date %> | <%= seat.showtime.start_time %></td>
    <td>Row: <%= seat.row %> | Chair: <%= seat.chair_letter %></td>
    <td><%= link_to 'Show', [seat.showtime, seat] %></td>
    <td><%= link_to 'Give Up Ticket', give_up_seat_path(seat.showtime, seat) %></td>
    <!-- <td><%#= link_to 'Edit', [:edit, seat.showtime, seat] %></td> -->
    <!-- <td><%#= link_to 'Destroy', [seat.showtime, seat], method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
  </tr>
<% end %>
</table>


<%= link_to 'Edit your Account Settings', edit_user_path(@user) %> |
<%= link_to 'Back to All Movies', movies_path %>