config/routes.rb
TheaterApp::Application.routes.draw do
  match "signup" => 'users#new', :as => "signup"
  match "login" => 'sessions#new', :as => "login"
  match "logout" => 'sessions#destroy', :as => "logout"

  get "showtimes/:showtime_id/seats/:id/save/" => 'seats#save', :as => 'save_seat'
  get "showtimes/:showtime_id/seats/:id/give_up_seat/" => 'seats#give_up_seat', :as => 'give_up_seat'

  resources :users
  resources :movies
  resources :showtimes do
    resources :seats
  end
  resources :sessions, :except => [:edit, :update, :index]

  root :to => "movies#index"

end

app/models/showtime.rb
# == Schema Information
#
# Table name: showtimes
#
#  id         :integer          not null, primary key
#  date       :date
#  start_time :time
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  movie_id   :integer
#

class Showtime < ActiveRecord::Base
  belongs_to :movie
  has_many :seats
  has_many :users, :through => :seats


  attr_accessible :date, :start_time, :movie_id
  validates :date, :presence => true
  validates :start_time, :presence => true
  validates :movie_id, :presence => true

  def available_seats?
    unreserved_seats = self.seats.where(:user_id => nil)

    unreserved_seats.length > 0
  end
end

app/controllers/showtimes_controller.rb
class ShowtimesController < ApplicationController

  skip_before_filter :require_authentication
  skip_before_filter :require_admin_authentication

  def index
    @showtimes = Showtime.all

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  def new
    @showtime = Showtime.new
    @movies = Movie.all

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  def create
    @showtime = Showtime.new(params[:showtime])

    respond_to do |format|
      if @showtime.save
        format.html { redirect_to @showtime, notice: 'Showtime was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.js
      end
    end
  end

  def show
    @showtime = Showtime.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  def edit
    @showtime = Showtime.find(params[:id])
    @movies = Movie.all
  end

  def update
    @showtime = Showtime.find(params[:id])

    respond_to do |format|
      if @showtime.update_attributes(params[:showtime])
        format.html { redirect_to @showtime, notice: 'Showtime was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js
      end
    end
  end

  def destroy
    @showtime = Showtime.find(params[:id])
    @showtime.destroy

    respond_to do |format|
      format.html { redirect_to showtimes_url }
      format.js
    end
  end
end

app/helpers/showtimes_helper.rb
module ShowtimesHelper
end

app/views/showtimes/_form.html.erb
<%= form_for(@showtime) do |f| %>
  <% if @showtime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@showtime.errors.count, "error") %> prohibited this showtime from being saved:</h2>

      <ul>
      <% @showtime.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :movie_id %><br />
    <%= f.select :movie_id, options_from_collection_for_select(@movies, 'id', 'name')  %>
  </div>

  <% if !@seat.nil? %>
    <input type="hidden" name="seat_id" value="<%= @seat.id %>">
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/showtimes/edit.html.erb
<h1>Showtimes#edit</h1>
<p>Find me in app/views/showtimes/edit.html.erb</p>

<h1>Editing showtime</h1>

<%= render 'form' %>

<%= link_to 'Show', @showtime %> |
<%= link_to 'Back', showtimes_path %>

app/views/showtimes/index.html.erb
<h1>Showtimes#index</h1>
<p>Find me in app/views/showtimes/index.html.erb</p>


<h1>Listing Showtimes</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Time</th>
    <th>Movie</th>
    <th></th>
    <th></th>
    <!-- <th></th> -->
    <!-- <th></th> -->
  </tr>

<% @showtimes.sort.each do |showtime| %>
  <tr>
    <td><%= showtime.date %></td>
    <td><%= showtime.start_time %></td>
    <td><%= showtime.movie.name %></td>
    <td><%= link_to 'Show', showtime %></td>
    <td><%= link_to 'See available Seats', showtime_seats_path(showtime) %></td>
    <!-- <td><%#= link_to 'Edit', edit_movie_path(showtime) %></td> -->
    <!-- <td><%#= link_to 'Destroy', showtime, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
  </tr>
<% end %>
</table>

<br />

<!-- <%#= link_to 'New Showtime', new_showtime_path %> -->

app/views/showtimes/new.html.erb
<h1>Showtimes#new</h1>
<p>Find me in app/views/showtimes/new.html.erb</p>

<h1>New Showtime</h1>

<%= render 'form' %>

<%= link_to 'Back to all Showtimes', showtimes_path %>

app/views/showtimes/show.html.erb
<h1>Showtimes#show</h1>
<p>Find me in app/views/showtimes/show.html.erb</p>

<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @showtime.date %>
</p>

<p>
  <b>Start Time:</b>
  <%= @showtime.start_time %>
</p>


<p>
  <b>Movie:</b>
  <%= @showtime.movie.name %>
</p>


<%= link_to 'See available Seats', showtime_seats_path(@showtime) %> |
<%= link_to 'Edit', edit_showtime_path(@showtime) %> |
<%= link_to 'Back to All Showtimes', showtimes_path %>