config/routes.rb
TheaterApp::Application.routes.draw do
  match "signup" => 'users#new', :as => "signup"
  match "login" => 'sessions#new', :as => "login"
  match "logout" => 'sessions#destroy', :as => "logout"

  get "showtimes/:showtime_id/seats/:id/save/" => 'seats#save', :as => 'save_seat'
  get "showtimes/:showtime_id/seats/:id/give_up_seat/" => 'seats#give_up_seat', :as => 'give_up_seat'

  resources :users
  resources :movies
  resources :showtimes do
    resources :seats
  end
  resources :sessions, :except => [:edit, :update, :index]

  root :to => "movies#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheaterApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <div class="row">
    <section class="top-bar-section">
      <ul class="left">
        <li class="active"><a href="/"><%= image_tag("white_home.png") %></a></li>
        <li class="divider"></li>
          <% if current_user %>
            <li><a href="#">Logged in as <%= current_user.email %></a></li>
            <li class="divider"></li>
            <li><a href="#"><%= link_to "My Reservations", user_path(current_user) %></a></li>
            <li class="divider"></li>
            <li><%= link_to "Log Out", logout_path %></li>
            <li class="divider"></li>
          <% else %>
            <li><%= link_to "Signup", login_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Log In", login_path %></li>
            <li class="divider"></li>
          <% end %>
      </ul>
    </section>
  </div>
  </nav>

  <% unless flash[:notice].blank? %>
    <p id="flash_notice"><%= flash[:notice] %></p>
  <% end %>

  <% unless flash[:alert].blank? %>
    <p id="flash_alert"><%= flash[:alert] %></p>
  <% end %>

<%= yield %>

</body>
</html>